[package]
name = "taiji_test_utils"
description = "Utility functions used in Taiji test functions"
version = "0.52.0-dan.1"
authors = ["The Taiji Development Community"]
edition = "2018"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
taiji_shutdown = { path = "../shutdown" }
taiji_comms = { path = "../../comms/core" }

futures = { version = "^0.3.1" }
rand = "0.8"
tokio = { version = "1.23", features = ["rt-multi-thread", "time", "sync"] }
tempfile = "3.1.0"

[dev-dependencies]
futures-test = { version = "^0.3.1" }
