[package]
name = "taiji_shutdown"
description = "A convenient shutdown signal"
authors = ["The Taiji Development Community"]
repository = "https://github.com/onsight-tech-services/taiji"
homepage = "https://taiji.com"
readme = "README.md"
license = "BSD-3-Clause"
version = "0.52.0-pre.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "^0.3"

[dev-dependencies]
tokio = { version = "1", default-features = false, features = ["rt", "macros"] }
