[package]
name = "taiji_common_types"
authors = ["The Taiji Development Community"]
description = "Taiji cryptocurrency common types"
license = "BSD-3-Clause"
version = "0.52.0-dan.1"
edition = "2018"

[dependencies]
tari_crypto = { version = "0.18" }
tari_utilities = { version = "0.5" }
taiji_common = {  path = "../../common" }


chacha20poly1305 = "0.10.1"
borsh = "0.10"
digest = "0.10"
lazy_static = "1.4.0"
newtype-ops = "0.1"
rand = "0.8"
serde = { version = "1.0.106", features = ["derive"] }
thiserror = "1.0.29"
tokio = { version = "1.23", features = ["time", "sync"] }
base64 = "0.21.0"
blake2 = "0.10"
