[package]
name = "minotaiji_wallet_grpc_client"
version = "0.1.0"
edition = "2021"
description = "Base node GRPC client"
authors = ["The Taiji Development Community"]
repository = "https://github.com/tari-project/tari"
homepage = "https://taiji.com"
readme = "README.md"
license = "BSD-3-Clause"

[dependencies]
minotaiji_app_grpc = { path = "../../../applications/minotaiji_app_grpc" }
taiji_common_types = { path = "../../../base_layer/common_types" }

thiserror = "1.0.35"
tonic = { version = "0.6", default-features = false, features = ["codegen", "transport"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros"] }
