[package]
name = "minotaiji_wallet_ffi"
authors = ["The Taiji Development Community"]
description = "Taiji cryptocurrency wallet C FFI bindings"
license = "BSD-3-Clause"
version = "0.52.0-pre.0"
edition = "2018"

[dependencies]
taiji_core = {  path = "../../base_layer/core", default-features = false, features = ["taiji_mmr", "transactions"] }
taiji_common = { path="../../common" }
taiji_common_types = { path="../common_types" }
taiji_comms = {  path = "../../comms/core", features = ["c_integration"]}
taiji_comms_dht = {  path = "../../comms/dht", default-features = false }
tari_crypto = { version = "0.18" }
taiji_key_manager = {  path = "../key_manager" }
taiji_p2p = {  path = "../p2p" }
taiji_script = { path = "../../infrastructure/taiji_script" }
taiji_shutdown = {  path = "../../infrastructure/shutdown" }
tari_utilities = { version = "0.5" }
minotaiji_wallet = {  path = "../wallet", features = ["c_integration"]}
taiji_contacts = { path = "../../base_layer/contacts" }

chacha20poly1305 = "0.10.1"
chrono = { version = "0.4.19", default-features = false, features = ["serde"] }
futures =  { version = "^0.3.1", features =["compat", "std"]}
libc = "0.2.65"
log = "0.4.6"
log4rs = { git = "https://github.com/tari-project/log4rs.git", features = ["console_appender", "file_appender", "yaml_format"] }
rand = "0.8"
thiserror = "1.0.26"
tokio = "1.23"
num-traits = "0.2.15"
itertools = "0.10.3"
zeroize = "1"
serde_json = "1.0"

[target.'cfg(target_os="android")'.dependencies]
openssl = { version = "0.10.55", features = ["vendored"] }

[lib]
crate-type = ["staticlib","cdylib"]

[dev-dependencies]
tempfile = "3.1.0"
lazy_static = "1.3.0"
taiji_key_manager = {  path = "../key_manager" }
taiji_common_types = {  path = "../../base_layer/common_types"}
taiji_test_utils = {  path = "../../infrastructure/test_utils"}
taiji_service_framework = { path = "../../base_layer/service_framework" }
borsh = "0.10"

[build-dependencies]
cbindgen = "0.24.3"
taiji_common = { path = "../../common", features = ["build", "static-application-info"] }
