[package]
name = "taiji_metrics"
description = "Taiji metrics"
version = "0.1.0"
edition = "2021"
authors = ["The Taiji Development Community"]
repository = "https://github.com/taiji-project/taiji"
homepage = "https://taiji.com"
readme = "README.md"
license = "BSD-3-Clause"

[dependencies]
log = { version = "0.4.14", optional = true }
once_cell = "1.8.0"
prometheus = "0.13.0"

futures = { version = "0.3.15", default-features = false, optional = true }
reqwest = { version = "0.11.4", default-features = false, optional = true }
tokio = { version = "1", optional = true, features = ["time", "rt-multi-thread"] }
warp = { version = "0.3.1", optional = true, default-features = false }
thiserror = "1.0.25"
anyhow = { version = "1.0.53", optional = true }

[features]
pull = ["warp"]
push = ["reqwest", "tokio"]
server = ["pull", "push", "log", "anyhow", "futures"]
