[package]
name = "taiji_service_framework"
version = "0.52.0-pre.0"
authors = ["The Taiji Development Community"]
description = "The Taiji communication stack service framework"
repository = "https://github.com/onsight-tech-services/taiji"
edition = "2018"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
taiji_shutdown = {  path = "../../infrastructure/shutdown" }

anyhow = "1.0.53"
async-trait = "0.1.50"
futures = { version = "^0.3.16", features = ["async-await"] }
log = "0.4.8"
thiserror = "1.0.26"
tokio = { version = "1.23", features = ["rt"] }
tower-service = { version = "0.3" }

[dev-dependencies]
taiji_test_utils = {  path = "../../infrastructure/test_utils" }

tokio = { version = "1.23", features = ["rt-multi-thread", "macros", "time"] }
futures-test = { version = "0.3.3" }
tower = "0.4"
