[book]
authors = ["Philip Robinson", "Byron Hambly", "SW van Heerden"]
language = "en"
multilingual = false
src = "src"
title = "Taiji Protocol Developer Documentation"

[output.html]
mathjax-support=true
theme = "src/theme"
